### PR TITLE
Add the option to not kick players when their party fails to move them.

### PR DESCRIPTION
**Pull request by TheDeafCreeper**
I have not tested this version yet (I'll do that at the same time I test the TP change), however it adds a new config option for parties (`switching-servers.kick-on-failure` [Default's `true` aka current behavior]) that decides whether or not a player is removed from the party if they fail to move with it, or if they just receive an error.

The relevant message was also added.
`following_failed: "<red>There was an issue following your party!</red>"`

### CODE REVIEW

**Comment by nathan-i-martin** [comment]
Can you implement this and #48 against [v0.8.0-stacked](https://github.com/Aelysium-Group/rusty-connector/tree/v0.8.0-stacked) instead of main?

**Comment by nathan-i-martin** [comment]
For future PRs too, plz merge into at least development. Tho if there's a branch for the upcoming version, that's even better

**Comment by TheDeafCreeper** [comment]
Alright converted to 0.8.0, cannot test it at the moment though because it does not seem to compile due to an unrelated issue.

**Comment by nathan-i-martin** [comment]
Reopening

**Comment by nathan-i-martin** [comment]
Reopening

**Comment by nathan-i-martin** [comment]
Woops I forgot to switch the branch on this before merging. Could you resubmit this PR into `v0.8.0`?

**Pull request closed without merging**
